apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: ossm-example-body-extension
spec:
  pluginConfig:
    secret-word: secret
  url: oci://quay.io/isanchez/ossm-example-body-extension:1.0.0
  priority: 100
  phase: STATS
  selector:
    matchLabels:
      app: httpbin